### ISSUE TITLE
Where do you work question

### ISSUE THREAD

**Issue by rlonka** [nordic-rse/RSE_intro_survey#1]
How should we proceed with Where do you work question. Should we compile huge list of all universities and research institutes at Nordic countries? Should we just leave text field and then deal with it later?

**Comment by bast** [comment]
If there is a standard list, we can use it but I would not compile an own list and in this case rather go for free form which we would need to clean up later.

**Comment by annefou** [comment]
Yes but maybe we could give some recommendations. For instance:
- use english only (no offense but if we need to translate in all the nordic languages and dialects...)
- use "University of Oslo" instead of "Oslo University" 
- fill the university or company full name only (no department, etc.)

**Comment by rlonka** [comment]
Could you verify the text?
