### ISSUE TITLE
Intro and final  text

### ISSUE THREAD

**Issue by rlonka** [nordic-rse/RSE_intro_survey#10]
Hi,
I think @bast has suggested to use same text for Survey intro as we have for email which I thing is good idea (just removing the link to survey itself...)

How about after survey text?
Should we add it to repo as text?
Or just directly ti survey? I guess we should inform when it will finish ( probably to add it email and intro?) and just say thank you at end?

**Comment by wikfeldt** [comment]
Hi, I'm not completely following. What after survey text is that?

**Comment by rlonka** [comment]
Hi, after you submit survey there is good bay page, atm the text is:

> Thank you for your answers. If you wish to know more, please visit https://nordic-rse.org
 
But maybe we want to say more?

**Comment by annefou** [comment]
I would leave it as it is now.

**Comment by rlonka** [comment]
should we also include invitation to join the RSE into some text (intro or after survey)?
Something like: 'if you interested in RSE please help us to build the community and/or  join our effort'...

**Comment by bast** [comment]
Yes, good idea. Just one-two sentences on how people can get involved.

**Comment by rlonka** [comment]
How about something like this:

> We encourage anyone to join our effort and to help building community to raise awareness of the importance of software in research, and the vital role RSEs play in creating this software. Get in touch via slack, mailing list or contact as at contact@nordic-rse.org.

Maybe it should be added to intro/email text? 

Second option is to create web page similar to [http://rse.ac.uk/join-us/](http://rse.ac.uk/join-us/)
and use it.

**Comment by bast** [comment]
I prefer the join-us page and we refer to it. Advantage is that we can use and refer to it also outside the survey.

**Comment by rlonka** [comment]
I agree, I have created issue for this [https://github.com/nordic-rse/nordic-rse.github.io/issues/7](https://github.com/nordic-rse/nordic-rse.github.io/issues/7)

**Comment by rlonka** [comment]
looks like done, it is also discussed in #11 so kind of redundant now. Therefore closing
