### ISSUE TITLE
Create short-link for survey

### ISSUE THREAD

**Issue by bast** [nordic-rse/RSE_intro_survey#12]
I think we should create a short-link to the survey with a nice URL which makes it easier to communicate it. E.g. using https://bitly.com which allows custom URLs.

**Comment by rlonka** [comment]
google can provide shorten url, f.e for our survey it could be [https://goo.gl/forms/qxNb80tWIBcphbkV2](https://goo.gl/forms/qxNb80tWIBcphbkV2), in butly it would be [https://bit.ly/2HWQ6uM](https://bit.ly/2HWQ6uM), each one should we use?

**Comment by bast** [comment]
In bitly you can change the "2HWQ6uM" to something custom and readable. As to Google, note this: https://www.theverge.com/2018/3/31/17184164/google-alphabet-url-shortening-service-closed

**Comment by rlonka** [comment]
ok, we should definitely  do that then!

**Comment by rlonka** [comment]
clsoing down, moved to  [https://github.com/nordic-rse/RSE_intro_survey/issues/11](https://github.com/nordic-rse/RSE_intro_survey/issues/11)
