### ISSUE TITLE
Email text

### ISSUE THREAD

**Issue by rlonka** [nordic-rse/RSE_intro_survey#2]
We need some accompanying text when we will send the survey via email.

**Comment by annefou** [comment]
Do you mean something like:

Are you a Research Software Engineer working in a Nordic Country? Do you work professionally in software in a research environment, at least partly writing code for other people? Your job title might be research/scientific programmer, application expert, facilitator, postdoctoral researcher, or research assistant. 

If so, please fill out [this short survey](...), being run by [NeIC CodeRefinery](http://coderefinery.org/) with the idea of understanding and helping to organize the Nordic RSE community: ....

**Comment by bast** [comment]
These things are important for me: 1) brevity, 2) the text should motivate what people get out of it if they participate, in other words why it might be good for them to participate, 3) we should indicate how we will use the data and 4) we should indicate how long the survey takes.

**Comment by rlonka** [comment]
good text, although I am not sure if we can use NeIC and CodeRefinery in the email, it can attract people but then we have to get agreement from both, isn't that?
Also many people does not know about RSE so maybe we should start with different sentense?

I definitely agree with all your points Radovan.
Do you have any examples from coderefinery surveys? We might also ask other int RSEs...

What could motivate people to fill this short survey?

I think we should the text is very important to get many people to fill the survey but is that really true?
I would not want to exaggerate this issue too... 
I have no experience with this...

**Comment by bast** [comment]
Can we perhaps reuse the text used in similar RSE surveys?

**Comment by rlonka** [comment]
I got reply form Canadian RSE:

Scientific research is vital to the lives of Canadians, and software has become increasingly crucial to this research.  For the past decade, CANARIE has been funding the development of specialized research software. To ensure that this funding program continues to meet the needs of Canada’s research community, we’d like to learn more about those of you who write this software and how to better support you.  Whether you develop software for research in an academic, government, non-profit or commercial environment - full-time or part-time - we’d like to hear from you.

CANARIE, in partnership with the UK’s Software Sustainability Institute (SSI), is pleased to invite you to participate in the Canadian Research Software Developers Survey.  The first 100 Canadian* research software developers who complete this short, 10-minute survey will receive a $20 Amazon gift certificate (limit of one per person). 

| Launch Survey |

All personally identifiable information will be kept private, with only aggregated results released publicly in a final report.  To be informed about the results of this survey and other items of interest to research software developers, visit https://www.canarie.ca/subscribe and sign up for the Research Software Newsletter.

* Not based in Canada? Residents of other countries are also welcome to participate in this survey as the SSI is collecting information about research software developers from around the globe. (edited)

**Comment by bast** [comment]
That's a very good starting point. I think we can reuse most of it, adjust a bit to the Nordic context, and off it goes :-)

**Comment by rlonka** [comment]
Please comment and/or edit:

Scientific research is vital to the lives of Nordics, and software has become increasingly crucial to this research. To ensure that the software development meet the needs of Nordic research community, we’d like to learn more about those of you who write this software and how to better support you. Whether you develop software for research in an academic, government, non-profit or commercial environment - full-time or part-time - we’d like to hear from you.

Nordic RSE (Research Software Engineering) , as part of International RSE network, is pleased to invite you to participate in this 5 minutes survey on Nordic Research Software.

| Launch Survey |

We do not collect any personally identifiable information.
To be informed about the results of this survey and other items of interest to research software developers, visit [http://nordic-rse.no](http://nordic-rse.no), Follow us on Twitter and/or sign up for the Nordic RSE  mailing list.

**Comment by rlonka** [comment]
we should add that the survey is very short... But I have not figure out where to add it

**Comment by annefou** [comment]
Yes I would mention it to encourage anyone who receive it to answer immediately. Otherwise it is forgotten...

**Comment by rlonka** [comment]
I agree with you @annefou , I just do not know where to put it... It would be nice if it will be very visible somehow...

**Comment by annefou** [comment]
I would add it in the last sentence before launching the survey. Something like:

Nordic RSE (Research Software Engineering) , as part of International RSE network is pleased to invite you to participate in a 5 minutes survey on Nordic Research Software.

| Launch Survey |

**Comment by rlonka** [comment]
good, I have edited the text

**Comment by bast** [comment]
Can we put the text into the repo? Then we can send PRs against it. Please wrap lines so that they are short :-)

**Comment by rlonka** [comment]
good idea, it is there

**Comment by bast** [comment]
I think this is now drafted. For new issues/questions, we can open more fine-grained issues.
