### ISSUE TITLE
Adding country question

### ISSUE THREAD

**Issue by rlonka** [nordic-rse/RSE_intro_survey#4]
Should we add question What country you work at? , it could be deducted from work place question, but it is more explicit and here we could have combo box: [Sweden, Norway, Finland, Denmark, Iceland] 
Btw, do we count Faeroe island and Greenland as a separate  countries?

**Comment by annefou** [comment]
Yes. we can have a combo box + Other with free text. I don't know if we should include other Baltic countries (Estonia, etc.).

**Comment by rlonka** [comment]
I have added countries, I do not think we should include Baltic, I think they could be another region
