### ISSUE TITLE
anonymous survey 

### ISSUE THREAD

**Issue by rlonka** [nordic-rse/RSE_intro_survey#7]
I thought to have the survey anonymous and not to collect any emails, if participant want they can sign to maillist.
One problem then might be there is no way to check someone completed survey more then once.
I do not think it will happen but I would like to open the issue anyway.
I would like to see your comments.

**Comment by bast** [comment]
You mean filling it out accidentally more than once?

**Comment by rlonka** [comment]
yes

**Comment by bast** [comment]
I don't think the risk is high. I think a much larger risk is filling it out less than once :-)
But it's critical that there is good feedback mechanism. Sometimes I fill out something and I am not sure whether it was "sent"/registered. If I then see the register button still, I might click it again "just to be sure".

**Comment by rlonka** [comment]
yes you right about filling less then once :)

Maybe I just see problem where there is none.

Do you think it is better idea to ask for email or do it anonymous? What are your experiences?

**Comment by bast** [comment]
If I imagine myself as the person filling out the survey, if I get asked for my email address, it's OK for me but I would like to know why. If it is only to avoid duplicates, it's perhaps not enough? I don't think duplicates will be a problem.

**Comment by rlonka** [comment]
ok, I think we will go for anonymous atm, I am closing this issue then
